[phases.setup]
aptPkgs = ["python3", "python-is-python3", "libnss3", "libatk1.0-0", "libatk-bridge2.0-0", "libcups2", "libgbm1", "libasound2", "libpangocairo-1.0-0", "libxss1", "libgtk-3-0", "libxshmfence1", "libglu1"]

[phases.install]
cmds = [
  "npm cache clean --force",
  "npm install express cookie",
  "npm install --legacy-peer-deps"
]

[phases.build]
cmds = ["npm rebuild"]

[start]
cmd = "node index.js"

[variables]
YOUTUBE_DL_SKIP_PYTHON_CHECK = "1"
NODE_ENV = "production"