
[phases.install]
cmds = [
  "npm cache clean --force",
  "npm install",
  "npm install --save express mongoose cloudinary dotenv cors"
]

[phases.build]
cmds = [
  "npm rebuild"
]

[start]
cmd = "node index.js"
healthcheck = {path = "/health", interval = "10s", timeout = "5s"}

[http]
port = 5000
routes = {"/health" = "GET"}

[variables]
NODE_ENV = "production"